export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS"
export const EDIT_TODO_VALUE = 'EDIT_TODO_VALUE'